name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t test-app ./app

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: 22
        timeout: 60s
        script_stop: true
        debug: true
        script: |
          echo "✅ Logged into EC2 as $(whoami)"
          cd ~/ci-demo || exit 1
          git pull origin main
          make deploy
